---
- name: Clone a github repository
  git:
    repo: "https://github.com/{{ item }}.git"
    dest: "$HOME/Documents/{{ item }}"
    clone: yes
    update: yes
  loop: "{{ Repos.GitHub }}"
  loop_control:
    label: "{{ item }}"
