---
- name: Get current Terminal profile.
  shell: defaults read com.apple.Terminal 'Default Window Settings'
  register: current_terminal_theme
  changed_when: false

- name: Ensure custom Terminal profile is added.
  shell: open templates/{{ macOSTerminalThemeName }}.terminal
  changed_when: false
  when: macOSTerminalThemeName not in current_terminal_theme.stdout

- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.Terminal 'Default Window Settings' -string '{{ macOSTerminalThemeName }}'
    - defaults write com.apple.Terminal 'Startup Window Settings' -string '{{ macOSTerminalThemeName }}'
  changed_when: false
  when: macOSTerminalThemeName not in current_terminal_theme.stdout
